"""Add ON DELETE CASCADE to invoice item

Revision ID: 0f51646da571
Revises: e0552d33142a
Create Date: 2025-06-25 01:31:47.870500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f51646da571'
down_revision = 'e0552d33142a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice_items', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('invoice_items_invoice_id_fkey'), 'invoice_items', type_='foreignkey')
    op.create_foreign_key(None, 'invoice_items', 'invoice', ['invoice_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice_items', type_='foreignkey')
    op.create_foreign_key(op.f('invoice_items_invoice_id_fkey'), 'invoice_items', 'invoice', ['invoice_id'], ['id'])
    op.alter_column('invoice_items', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
