"""Promjena user.py

Revision ID: 22035f9a404d
Revises: fae84549eaaf
Create Date: 2025-04-18 21:40:23.879699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22035f9a404d'
down_revision = 'fae84549eaaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
