"""Dodavanje novih tabela

Revision ID: 2c30c2eb291a
Revises: 22035f9a404d
Create Date: 2025-05-07 03:20:08.456184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c30c2eb291a'
down_revision = '22035f9a404d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('category',
    #sa.Column('id', sa.Integer(), nullable=False),
    #sa.Column('name', sa.String(length=64), nullable=False),
    #sa.PrimaryKeyConstraint('id'),
    #sa.UniqueConstraint('name')
    #)
    #op.create_table('vendor',
    #sa.Column('id', sa.Integer(), nullable=False),
    #sa.Column('vat_number', sa.String(length=20), nullable=False),
    #sa.Column('account_number', sa.String(length=50), nullable=False),
    #sa.Column('bank', sa.String(length=100), nullable=False),
    #sa.Column('vendor_name', sa.String(length=100), nullable=False),
    #sa.Column('adress', sa.String(length=200), nullable=False),
    #sa.PrimaryKeyConstraint('id'),
    #sa.UniqueConstraint('vat_number')
    #)
    #op.create_table('invoice',
    #sa.Column('firm_name', sa.String(length=100), nullable=False),
    #sa.Column('id', sa.Integer(), nullable=False),
    #sa.Column('date', sa.String(length=10), nullable=False),
    #sa.Column('quantity', sa.Integer(), nullable=False),
    #sa.Column('vat_number', sa.String(length=20), nullable=False),
    #sa.Column('account_number', sa.String(length=50), nullable=False),
    #sa.Column('iban', sa.String(length=20), nullable=False),
    #sa.Column('bank_name', sa.String(length=100), nullable=False),
    #sa.Column('unit_price', sa.Integer(), nullable=False),
    #sa.Column('vat_rate', sa.Float(), nullable=False),
    #sa.Column('vat_amount', sa.Float(), nullable=False),
    #sa.Column('firm_adress', sa.String(length=200), nullable=False),
    #sa.Column('total_excl_vat', sa.Float(), nullable=False),
    #sa.Column('total_incl_vat', sa.Float(), nullable=False),
    #sa.Column('photo_filename', sa.String(length=20), nullable=False),
    #sa.Column('vendor_id', sa.Integer(), nullable=False),
    #sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    #sa.PrimaryKeyConstraint('id'),
    #sa.UniqueConstraint('vat_number')
    #)
    #op.create_table('products',
    #sa.Column('id', sa.Integer(), nullable=False),
    #sa.Column('item_name', sa.String(length=100), nullable=False),
    #sa.Column('price', sa.Float(), nullable=False),
    #sa.Column('quantity', sa.Integer(), nullable=False),
    #sa.Column('unit_price', sa.Integer(), nullable=False),
    #sa.Column('total_excl_vat', sa.Float(), nullable=False),
    #sa.Column('category_id', sa.Integer(), nullable=False),
    #sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    #sa.PrimaryKeyConstraint('id')
    #)
    op.create_table('invoice_product',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('invoice_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_product')
    op.drop_table('products')
    op.drop_table('invoice')
    op.drop_table('vendor')
    op.drop_table('category')
    # ### end Alembic commands ###
