"""Dodavanje novih tabela blacklisttokens, categorybudgets, budgets, invoiceitems i measuringunits, te nadogradnja prethodno postojećih baza

Revision ID: 512482b369bd
Revises: 1f6d192512cb
Create Date: 2025-05-28 02:05:27.302478

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '512482b369bd'
down_revision = '1f6d192512cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('blackListTokens',
    #sa.Column('id', sa.Integer(), nullable=False),
    #sa.Column('token', sa.String(length=200), nullable=False),
    #sa.Column('createdAt', sa.DateTime(), nullable=False),
    #sa.Column('updatedAt', sa.DateTime(), nullable=False),
    #sa.PrimaryKeyConstraint('id'),
    #sa.UniqueConstraint('token')
    #)
    #op.create_table('budget',
    #sa.Column('id', sa.Integer(), nullable=False),
    #sa.Column('total_budget', sa.Float(), nullable=False),
    #sa.Column('spent_budget', sa.Float(), nullable=False),
    #sa.Column('year', sa.Integer(), nullable=False),
    #sa.Column('month', sa.Integer(), nullable=False),
    #sa.Column('createdAt', sa.DateTime(), nullable=False),
    #sa.Column('updatedAt', sa.DateTime(), nullable=False),
    #sa.PrimaryKeyConstraint('id')
    #)
    #op.create_table('measuringUnits',
    #sa.Column('id', sa.String(length=20), nullable=False),
    #sa.Column('measuring_unit', sa.String(length=15), nullable=False),
    #sa.Column('createdAt', sa.DateTime(), nullable=False),
    #sa.Column('updatedAt', sa.DateTime(), nullable=False),
    #sa.PrimaryKeyConstraint('id')
    #)
    op.create_table('categoryBudget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('budget_id', sa.Integer(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('spent_value', sa.Float(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    #op.drop_table('measuring_units')
    op.drop_table('category_budgets')
    op.drop_table('blacklist_tokens')
    op.drop_table('budgets')
    #op.add_column('category', sa.Column('createdAt', sa.DateTime(), nullable=False))
    #op.add_column('category', sa.Column('updatedAt', sa.DateTime(), nullable=False))
    op.drop_column('category', 'updated_at')
    op.drop_column('category', 'created_at')
    op.add_column('invoice', sa.Column('updatedAt', sa.DateTime(), nullable=False))
    op.alter_column('invoice', 'vat_number',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('invoice', 'account_number',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('invoice', 'iban',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('invoice', 'bank_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('invoice', 'photo_filename',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('invoice', 'vendor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('invoice', 'updated_at')
    #op.add_column('invoice_items', sa.Column('id', sa.Integer(), nullable=False))
    #op.add_column('invoice_items', sa.Column('createdAt', sa.DateTime(), nullable=False))
    #op.add_column('invoice_items', sa.Column('updatedAt', sa.DateTime(), nullable=False))
    #op.drop_column('invoice_items', 'updated_at')
    #op.drop_column('invoice_items', 'created_at')
    #op.drop_column('invoice_items', 'invoice_item_id')
    #op.add_column('products', sa.Column('createdAt', sa.DateTime(), nullable=False))
    #op.add_column('products', sa.Column('updatedAt', sa.DateTime(), nullable=False))
    #op.add_column('products', sa.Column('measuringUnits', sa.String(length=20), nullable=False))
    #op.drop_constraint('fk_products_measuring_unit_id', 'products', type_='foreignkey')
    #op.create_foreign_key(None, 'products', 'measuringUnits', ['measuringUnits'], ['id'])
    op.drop_column('products', 'measuring_unit_id')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    #op.add_column('users', sa.Column('firstName', sa.String(), nullable=False))
    #op.add_column('users', sa.Column('lastName', sa.String(), nullable=False))
    #op.add_column('users', sa.Column('createdAt', sa.DateTime(), nullable=False))
    #op.add_column('users', sa.Column('updatedAt', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'users', ['password'])
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'updated_at')
    #op.add_column('vendor', sa.Column('vendorCity', sa.String(length=50), nullable=False))
    #op.add_column('vendor', sa.Column('vendorTelephone', sa.String(length=20), nullable=False))
    #op.add_column('vendor', sa.Column('vendorEmail', sa.String(length=100), nullable=False))
    #op.add_column('vendor', sa.Column('vendorTransact', sa.String(length=100), nullable=False))
    #op.add_column('vendor', sa.Column('supportsAvans', sa.Boolean(), nullable=False))
    #op.add_column('vendor', sa.Column('createdAt', sa.DateTime(), nullable=False))
    #op.add_column('vendor', sa.Column('updatedAt', sa.DateTime(), nullable=False))
    op.drop_column('vendor', 'vendor_telephone')
    op.drop_column('vendor', 'vendor_transact')
    op.drop_column('vendor', 'vendor_city')
    op.drop_column('vendor', 'vendor_email')
    op.drop_column('vendor', 'supports_avans')
    op.drop_column('vendor', 'created_at')
    op.drop_column('vendor', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('vendor', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('vendor', sa.Column('supports_avans', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('vendor', sa.Column('vendor_email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('vendor', sa.Column('vendor_city', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('vendor', sa.Column('vendor_transact', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('vendor', sa.Column('vendor_telephone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('vendor', 'updatedAt')
    op.drop_column('vendor', 'createdAt')
    op.drop_column('vendor', 'supportsAvans')
    op.drop_column('vendor', 'vendorTransact')
    op.drop_column('vendor', 'vendorEmail')
    op.drop_column('vendor', 'vendorTelephone')
    op.drop_column('vendor', 'vendorCity')
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'updatedAt')
    op.drop_column('users', 'createdAt')
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'firstName')
    op.add_column('products', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('measuring_unit_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('fk_products_measuring_unit_id', 'products', 'measuring_units', ['measuring_unit_id'], ['id'])
    op.drop_column('products', 'measuringUnits')
    op.drop_column('products', 'updatedAt')
    op.drop_column('products', 'createdAt')
    op.add_column('invoice_items', sa.Column('invoice_item_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('invoice_items', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('invoice_items', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('invoice_items', 'updatedAt')
    op.drop_column('invoice_items', 'createdAt')
    op.drop_column('invoice_items', 'id')
    op.add_column('invoice', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('invoice', 'vendor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invoice', 'photo_filename',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('invoice', 'bank_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('invoice', 'iban',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('invoice', 'account_number',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('invoice', 'vat_number',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_column('invoice', 'updatedAt')
    op.add_column('category', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('category', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('category', 'updatedAt')
    op.drop_column('category', 'createdAt')
    op.create_table('budgets',
    sa.Column('id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('total_budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('spent_budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='budgets_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='blacklist_tokens_pkey'),
    sa.UniqueConstraint('token', name='blacklist_tokens_token_key')
    )
    op.create_table('category_budgets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('budget_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('total_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('spent_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], name='category_budgets_budget_id_fkey'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='category_budgets_category_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='category_budgets_pkey')
    )
    op.create_table('measuring_units',
    sa.Column('id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('measuring_unit', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='measuring_units_pkey')
    )
    op.drop_table('categoryBudget')
    op.drop_table('measuringUnits')
    op.drop_table('budget')
    op.drop_table('blackListTokens')
    # ### end Alembic commands ###
