"""Ponovno dodavanje korisnika i kategorija nakon popravka baze

Revision ID: 7828f10e0b8e
Revises: 512482b369bd
Create Date: 2025-05-28 02:45:25.973332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7828f10e0b8e'
down_revision = '512482b369bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measuring_units')
    #op.add_column('products', sa.Column('measuring_units_id', sa.String(length=20), nullable=False))
    #op.drop_constraint('products_measuringUnits_fkey', 'products', type_='foreignkey')
    #op.create_foreign_key(None, 'products', 'measuringUnits', ['measuring_units_id'], ['id'])
    #op.drop_column('products', 'measuringUnits')
    from sqlalchemy.sql import table, column
    from sqlalchemy import String

    users = table('users',
                  column('reset_password_link', String)
                  )

    op.execute(
        users.update().where(users.c.reset_password_link == None).values(reset_password_link="")
        )

    op.alter_column('users', 'reset_password_link',
                    existing_type=sa.String(length=255),
                    nullable=False
                    )
    
    op.alter_column('users', 'reset_password_link',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'reset_password_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('products', sa.Column('measuringUnits', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_measuringUnits_fkey', 'products', 'measuringUnits', ['measuringUnits'], ['id'])
    op.drop_column('products', 'measuring_units_id')
    op.create_table('measuring_units',
    sa.Column('id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('measuring_unit', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='measuring_units_pkey')
    )
    # ### end Alembic commands ###
