"""Finalni backup baze

Revision ID: 99feaa2bf680
Revises: e29edc643630
Create Date: 2025-07-09 16:54:28.107446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99feaa2bf680'
down_revision = 'e29edc643630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('spent_value', sa.Float(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('recurring', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('categoryBudget')
    op.add_column('budget', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'budget', 'category', ['category_id'], ['id'])
    op.add_column('invoice', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('users', 'reset_password_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('users_password_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_password_key', 'users', ['password'])
    op.alter_column('users', 'reset_password_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('invoice', 'updated_at')
    op.drop_constraint(None, 'budget', type_='foreignkey')
    op.drop_column('budget', 'category_id')
    op.create_table('categoryBudget',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('budget_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('spent_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], name='categoryBudget_budget_id_fkey'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='categoryBudget_category_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='categoryBudget_pkey')
    )
    op.drop_table('category_budgets')
    # ### end Alembic commands ###
