"""Add ON CASCADE delete to categories

Revision ID: e0552d33142a
Revises: fb413a28f4e6
Create Date: 2025-06-25 01:23:36.073195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0552d33142a'
down_revision = 'fb413a28f4e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invoice_category_id_fkey'), 'invoice', type_='foreignkey')
    op.create_foreign_key(None, 'invoice', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice', type_='foreignkey')
    op.create_foreign_key(op.f('invoice_category_id_fkey'), 'invoice', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###
