"""Initial migration

Revision ID: fae84549eaaf
Revises: 
Create Date: 2025-04-18 21:28:51.524993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae84549eaaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('users',
    sa.String()
    #sa.Column('id', sa.Integer(), nullable=False),
    #sa.Column('email', sa.String(length=120), nullable=False),
    #sa.Column('password', sa.String(length=128), nullable=False),
    #sa.Column('role', sa.Enum('admin', 'employee', name='roles', create_type=False), nullable=False),
    #sa.PrimaryKeyConstraint('id'),
    #sa.UniqueConstraint('email')
    #)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
