"""Added must_change_pwd to users model

Revision ID: fb413a28f4e6
Revises: 363dedbb1d7f
Create Date: 2025-06-25 00:42:30.121864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb413a28f4e6'
down_revision = '363dedbb1d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(op.f('budget_category_id_fkey'), 'budget', type_='foreignkey')
    op.drop_column('budget', 'category_id')
    op.alter_column('invoice', 'vendor_id',
               existing_type=sa.INTEGER(),
               nullable=False)


    #op.execute(
    #    """
    #    UPDATE invoice
    #    SET updated_at = created_at
    #    WHERE updated_at IS NULL
    #      AND created_at IS NOT NULL
    #    """
    #)

    #op.execute(
    #    """
    #    UPDATE invoice
    #    SET updated_at = now()
    #    WHERE updated_at IS NULL
    #    """
    #)
    #op.alter_column(
    #    'invoice',
    #    'updated_at',
    #    existing_type=sa.TIMESTAMP(),
    #    nullable=False
    #)
    #op.drop_column('invoice', 'firm_name')
    #op.drop_column('invoice_items', 'date')
    #op.drop_column('invoice_items', 'firm_name')


    #op.add_column(
    #    'users',
    #    sa.Column('must_change_pwd', sa.Boolean(), nullable=False, server_default=sa.text('true'))
    #)

    op.alter_column('users', 'must_change_pwd', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_change_pwd')
    op.add_column('invoice_items', sa.Column('firm_name', sa.VARCHAR(length=100), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('invoice_items', sa.Column('date', sa.DATE(), server_default=sa.text("'2025-06-24'::date"), autoincrement=False, nullable=False))
    op.add_column('invoice', sa.Column('firm_name', sa.VARCHAR(length=100), server_default=sa.text("'TEMP'::character varying"), autoincrement=False, nullable=False))
    op.alter_column('invoice', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('invoice', 'vendor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('budget', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('budget_category_id_fkey'), 'budget', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###
